[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_factory = "J41nXQ21D73QFAVpkD2FVVvAMEhRM37Z517NHhPzj6aV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
