[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_factory = "4GuhLkfXp3hJAeVrgozxhimPVvpJJ93MHpahqbnxAddG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
