[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_factory = "E72hAXTsSJn79Xb9mBB7kmK9VoX3HGNaoCyrqEqCE6dd"

[programs.localnet]
sol_factory = "E72hAXTsSJn79Xb9mBB7kmK9VoX3HGNaoCyrqEqCE6dd"

[programs.mainnet]
sol_factory = "E72hAXTsSJn79Xb9mBB7kmK9VoX3HGNaoCyrqEqCE6dd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
        