[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_factory = "2wj57nXtBwFAJS7mezos1mWirfVJWqxiqYAVtSt7W6F6"

[programs.devnet]
sol_factory = "2wj57nXtBwFAJS7mezos1mWirfVJWqxiqYAVtSt7W6F6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
