[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_factory = "4Fj9kuGYLye3pwCBYaXbuzocEy22gPWT5TcJVJ6JauUt"

[programs.devnet]
sol_factory = "4Fj9kuGYLye3pwCBYaXbuzocEy22gPWT5TcJVJ6JauUt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
